### ISSUE TITLE
Need help with BIOS set-up 

### ISSUE THREAD

**Issue by jackhu9527** [Baio1977/Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r#1]
"In Startup menu, set the following options:

UEFI/Legacy Boot: UEFI Only
CSM Support: No"

I have a X1 Tablet Gen 3 with similar specs and UEFI BIOS version installed (1.48).
However,I can't find the above options in Startup menu. The BIOS is in graphical mode instead of simple text mode - I didn't find an option to switch to simple text mode.

Please suggest how I could access the two options, thanks and have a great day.

**Comment by Baio1977** [comment]
There are NO longer those options, probably an evolution of the Bios.
I have updated the repository.
If you have trouble installing , make sure you have a Hackintosh-compatible SSD.
This is the most common problem.

**Comment by jackhu9527** [comment]
> There are NO longer those options, probably an evolution of the Bios.
> I have updated the repository.
> If you have trouble installing , make sure you have a Hackintosh-compatible SSD.
> This is the most common problem.

Thanks for your prompt response, appreciated.

I have returned my X1 tablet to the seller(bought as a pre-owned device). Great design language, poor keyboard connectivity among other things.

**Comment by Baio1977** [comment]
For me the best Hackintosh I've ever had......
EVERYTHING works and is perfect in every use......
