### ISSUE TITLE
iServices & USB issue

### ISSUE THREAD

**Issue by dusi12** [Baio1977/Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r#3]
Hi Baio!

First of all I would like to thank you for your work, it is wonderful and made it easy to run Hackintosh on a really specific hardware.
But I have a few issues and would love to hear your suggestions:

1. I can't get iServices (iMessage, AirDrop, Handoff, Continuity, Sync messages from iCloud, etc.) to work, [tried the suggestions here](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html) but didn't helped (changed the model to MacBookPro15,4, found a valid not used SN, so that should be fine.), it is possible to make it work with the Intel WiFi chip?

2. USB seems not fully working (maybe it is related to my first problem), in Hackintool I only see the Sunrise Point-LP Controller and if I plug in my iPhone for example it is only charging, not showing up in finder, can't use hotspot over USB, etc., USB drives not showing up. Also the overall performance of the system varies, sometimes fluid and fast, sometimes webpages loading for minutes (simple sites nothing special, my internet & network is fine, speedtest.net is OK) and moving in the system preferences is also slow (logging in to iCloud for example).

Here is a screenshot of my USB section from Hackintool:
<img width="937" alt="Képernyőfotó 2024-04-05 - 20 13 43" src="https://github.com/Baio1977/Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r/assets/115371907/a3683278-f3ff-4215-a868-722c0addfabf">

My X1 Tablet Gen 3 is a little different from yours, it has a i5-8350U, but that shouldn't be a problem.

Thanks for your reply,

Adam

**Comment by Baio1977** [comment]
Hi thanks for the support.
From the hackintool images I don't see the active TB3, furthermore attach ioreg and then put USBInjectAll in place of the USB kext and repeat ioreg and hackintool photos.
X1 Tablet provides many different configurations for USB as some devices in X1 Tablet are mounted under I2C or under USB for example the IR webcam in my laptop is I2C and unusable while in others it is under USB
