### ISSUE TITLE
Palm rejection

### ISSUE THREAD

**Issue by bweh** [Baio1977/Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r#4]
This is a very specific question, but is palm rejection working when writing on the tablet with the stylus? I want to know if it can be used like an iPad for drawing and annotating

**Comment by Baio1977** [comment]
Everything works, except the screen rotation, even Sequoia works well

https://github.com/user-attachments/assets/88861495-5100-44e6-8307-7f633a89c2ba
